import ExcelJS from "exceljs";
import {reportFilter,statusLabels} from "@/lib/reporting";
import {latestAssignmentOrder} from "@/lib/permissions";
import {NextResponse} from "next/server";
import {prisma} from "@/lib/prisma";
import {getCurrentUser} from "@/lib/auth";

export async function GET(request:Request){try{const user=await getCurrentUser();if(!user||!['ADMIN','SUPERADMIN'].includes(user.role))return NextResponse.json({error:"เฉพาะผู้ดูแลระบบเท่านั้น"},{status:403});const url=new URL(request.url);let filter;try{filter=reportFilter(Object.fromEntries(Array.from(url.searchParams.keys(),key=>{const values=url.searchParams.getAll(key);return [key,values.length>1?values:values[0]];})));}catch{return NextResponse.json({error:"ตัวกรองไม่ถูกต้อง"},{status:400});}
 const tickets=await prisma.ticket.findMany({where:filter.where,include:{building:true,category:true,reporter:true,assignments:{orderBy:latestAssignmentOrder,take:1,include:{technician:true}},evaluation:true},orderBy:{createdAt:'desc'}});
 const book=new ExcelJS.Workbook();book.creator="BRU Fondue";book.created=new Date();const sheet=book.addWorksheet("รายงานคำร้อง",{views:[{state:'frozen',ySplit:1}]});sheet.columns=[['รหัสคำร้อง','ticketCode',24],['หัวข้อปัญหา','title',34],['หมวดหมู่','category',24],['สถานที่','location',36],['อาคาร','building',34],['ความเร่งด่วน','priority',16],['สถานะ','status',20],['ผู้แจ้ง','reporter',24],['เบอร์โทร','phone',18],['ช่างผู้รับผิดชอบ','technician',26],['วันที่แจ้ง','createdAt',21],['วันที่เสร็จ','resolvedAt',21],['คะแนน','score',12],['ข้อคิดเห็น','comment',34]].map(([header,key,width])=>({header:String(header),key:String(key),width:Number(width)}));
 sheet.getRow(1).font={bold:true,color:{argb:'FFFFFFFF'}};sheet.getRow(1).fill={type:'pattern',pattern:'solid',fgColor:{argb:'FF312E81'}};sheet.getRow(1).alignment={vertical:'middle'};sheet.autoFilter={from:'A1',to:'N1'};
 for(const t of tickets)sheet.addRow({ticketCode:t.ticketCode,title:t.title,category:t.category.name,location:t.room||t.locationNote||t.building.name,building:t.building.name,priority:t.priority,status:statusLabels[t.status]||t.status,reporter:t.reporter.name,phone:t.reporter.phoneNumber||'-',technician:t.assignments[0]?.technician.name||'ยังไม่ได้มอบหมาย',createdAt:t.createdAt,resolvedAt:t.resolvedAt||null,score:t.evaluation?.score||null,comment:t.evaluation?.comment||'-'});
 sheet.getColumn('K').numFmt='dd/mm/yyyy hh:mm';sheet.getColumn('L').numFmt='dd/mm/yyyy hh:mm';sheet.eachRow((row,index)=>{row.alignment={vertical:'top',wrapText:true};if(index>1&&index%2===0)row.fill={type:'pattern',pattern:'solid',fgColor:{argb:'FFF8FAFC'}};});const buffer=await book.xlsx.writeBuffer();const date=new Date().toISOString().slice(0,10);return new NextResponse(new Uint8Array(buffer),{headers:{'Cache-Control':'private, no-store','Content-Type':'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','Content-Disposition':`attachment; filename="BRU-Fondue-Report-${date}.xlsx"`}});
 }catch(error){console.error('Export Excel error',error);return NextResponse.json({error:'ไม่สามารถสร้างไฟล์ Excel ได้'},{status:500});}}
