"use client";
import { useState } from "react";
import Link from "next/link";
import { validCoordinates } from "@/lib/coordinates";
interface TicketItem{id:string;ticketCode:string;title:string;status:string;priority:string;latitude:number|null;longitude:number|null;building:{name:string};category:{name:string};reporter:{name:string};images:{imageUrl:string;imageType:string}[];assignments:{technician:{name:string}}[]}
export interface AdminCampusMapProps{tickets:TicketItem[]}
const bounds={south:14.984586356558806,west:103.09295654296875,north:14.995198836057886,east:103.10394287109375};
const clamp=(value:number)=>Math.max(0,Math.min(1,value));
const markerColor=(status:string)=>status==="COMPLETED"?"#10b981":status==="IN_PROGRESS"||status==="WAITING_PARTS"?"#f59e0b":["REJECTED","CANCELLED"].includes(status)?"#64748b":"#ef4444";
export default function AdminCampusMap({tickets}:AdminCampusMapProps){const valid=tickets.filter(t=>validCoordinates(t.latitude,t.longitude));const [selected,setSelected]=useState<TicketItem|null>(null);return <div className="relative overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-xs"><div className="relative mx-auto aspect-square w-full max-w-[42rem] bg-slate-100"><img src="/campus-map.png" alt="แผนที่ภาพรวมมหาวิทยาลัยราชภัฏบุรีรัมย์" className="h-full w-full object-fill" draggable={false}/>{valid.map(t=>{const left=clamp((t.longitude!-bounds.west)/(bounds.east-bounds.west))*100;const top=clamp((bounds.north-t.latitude!)/(bounds.north-bounds.south))*100;return <button key={t.id} type="button" onClick={()=>setSelected(t)} title={`${t.ticketCode}: ${t.title}`} aria-label={`${t.ticketCode} ${t.title}`} className="absolute grid h-7 w-7 -translate-x-1/2 -translate-y-full place-items-center rounded-full border-2 border-white text-white shadow-md transition-transform hover:scale-125" style={{left:`${left}%`,top:`${top}%`,backgroundColor:markerColor(t.status)}}><span className="h-2 w-2 rounded-full bg-white"/></button>})}{selected&&<div className="absolute bottom-3 left-3 right-3 z-10 rounded-xl border border-slate-200 bg-white/95 p-4 shadow-xl backdrop-blur-sm sm:left-auto sm:w-96"><button type="button" onClick={()=>setSelected(null)} className="absolute right-2 top-2 h-9 w-9 rounded-lg text-slate-500" aria-label="ปิด">×</button><p className="font-mono text-sm font-semibold text-indigo-600">{selected.ticketCode}</p><h3 className="pr-8 text-lg font-bold">{selected.title}</h3><p className="mt-1 text-sm text-slate-600">{selected.building.name} · {selected.category.name}</p><p className="text-sm text-slate-500">ผู้แจ้ง: {selected.reporter.name}</p><Link href={`/tickets/${selected.id}`} className="mt-3 inline-flex rounded-lg bg-slate-900 px-4 py-2 text-sm font-semibold text-white">ดูรายละเอียดคำร้อง</Link></div>}</div><div className="flex flex-wrap gap-x-4 gap-y-2 border-t border-slate-200 p-3 text-xs text-slate-600"><span>🔴 รอรับเรื่อง</span><span>🟡 กำลังดำเนินการ/รออะไหล่</span><span>🟢 เสร็จสิ้น</span><span>⚪ ยกเลิก/ไม่รับดำเนินการ</span></div><p className="border-t border-slate-100 p-3 text-xs text-slate-600">แตะหมุดเพื่อดูข้อมูลคำร้อง · ไม่แสดงรายการที่ไม่มีพิกัด {tickets.length-valid.length} รายการ</p></div>}
