"use client";
import { useState } from "react";
interface Props { initialLat?:number; initialLng?:number; onLocationSelect:(lat:number,lng:number)=>void }
const bounds={south:14.984586356558806,west:103.09295654296875,north:14.995198836057886,east:103.10394287109375};
const clamp=(value:number)=>Math.max(0,Math.min(1,value));
const position=(lat:number,lng:number)=>({left:`${clamp((lng-bounds.west)/(bounds.east-bounds.west))*100}%`,top:`${clamp((bounds.north-lat)/(bounds.north-bounds.south))*100}%`});
export default function LocationPickerMap({initialLat=14.9928,initialLng=103.1025,onLocationSelect}:Props){
 const [lat,setLat]=useState(initialLat),[lng,setLng]=useState(initialLng),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const select=(nextLat:number,nextLng:number)=>{setLat(nextLat);setLng(nextLng);setError("");onLocationSelect(nextLat,nextLng)};
 const selectFromMap=(event:React.MouseEvent<HTMLButtonElement>)=>{const rect=event.currentTarget.getBoundingClientRect();const x=clamp((event.clientX-rect.left)/rect.width);const y=clamp((event.clientY-rect.top)/rect.height);select(bounds.north-y*(bounds.north-bounds.south),bounds.west+x*(bounds.east-bounds.west))};
 const useCurrentLocation=()=>{if(!window.isSecureContext||!navigator.geolocation){setError("อุปกรณ์นี้ไม่รองรับ GPS กรุณาแตะเลือกจุดบนแผนที่");return}setBusy(true);setError("");navigator.geolocation.getCurrentPosition(({coords})=>{select(coords.latitude,coords.longitude);setBusy(false)},reason=>{setError(reason.code===reason.PERMISSION_DENIED?"กรุณาอนุญาตตำแหน่ง หรือแตะเลือกจุดบนแผนที่":"ระบุตำแหน่งไม่ได้ กรุณาแตะเลือกจุดบนแผนที่");setBusy(false)},{enableHighAccuracy:true,timeout:15000,maximumAge:30000})};
 return <div className="space-y-3"><div className="flex flex-wrap items-center justify-between gap-3 text-sm"><span>ตำแหน่ง: <output>{lat.toFixed(6)}, {lng.toFixed(6)}</output></span><button type="button" disabled={busy} onClick={useCurrentLocation} className="rounded-lg border border-slate-300 bg-white px-3 py-2 font-semibold hover:bg-slate-50 disabled:opacity-50">{busy?"กำลังหาตำแหน่ง…":"ใช้ตำแหน่งปัจจุบัน"}</button></div>{error&&<p role="alert" className="rounded-lg bg-red-50 px-3 py-2 text-sm text-red-700">{error}</p>}<button type="button" onClick={selectFromMap} className="relative block aspect-square w-full max-w-[32rem] overflow-hidden rounded-xl border border-slate-300 bg-slate-100 p-0 text-left shadow-sm" aria-label="แตะบนแผนที่เพื่อเลือกตำแหน่ง"><img src="/campus-map.png" alt="แผนที่มหาวิทยาลัยราชภัฏบุรีรัมย์" className="h-full w-full object-fill" draggable={false}/><span className="absolute h-6 w-6 -translate-x-1/2 -translate-y-full rounded-full border-[5px] border-white bg-indigo-600 shadow-lg" style={position(lat,lng)} aria-hidden="true"/></button><p className="text-sm text-slate-600">แตะตำแหน่งบนแผนที่เพื่อวางหมุด ระบบจะบันทึกละติจูดและลองจิจูดให้อัตโนมัติ</p></div>;
}
