"use client";
import {useRef,useState} from 'react';
import {useRouter} from 'next/navigation';
import dynamic from 'next/dynamic';
type Building={id:number;name:string;code:string;defaultLat:number|null;defaultLng:number|null};
type Category={id:number;name:string;description:string|null;icon:string|null;defaultTechnicianId:string|null};
type Technician={id:string;name:string;department:string|null};
type Editor={kind:'building'|'category';id?:number;name:string;code:string;description:string;lat:string;lng:string;defaultTechnicianId:string;expected?:string};
const fresh=(kind:Editor['kind']):Editor=>({kind,name:'',code:'',description:'',lat:'',lng:'',defaultTechnicianId:''});
const LocationPickerMap=dynamic(()=>import('./LocationPickerMap'),{ssr:false,loading:()=><div className="flex h-72 items-center justify-center rounded-xl border border-slate-200 bg-slate-50 text-sm text-slate-500">กำลังโหลดแผนที่…</div>});
function coordinate(value:string,fallback:number,min:number,max:number){const parsed=Number(value);return value.trim()!==''&&Number.isFinite(parsed)&&parsed>=min&&parsed<=max?parsed:fallback;}
export default function MasterDataManager({buildings,categories,technicians}:{buildings:Building[];categories:Category[];technicians:Technician[]}){
 const router=useRouter();const [editor,setEditor]=useState<Editor|null>(null);const [error,setError]=useState('');const [success,setSuccess]=useState('');const [busy,setBusy]=useState(false);const lock=useRef(false);const formRef=useRef<HTMLFormElement>(null);
 function open(value:Editor){setEditor(value);setError('');setSuccess('');requestAnimationFrame(()=>{formRef.current?.scrollIntoView({block:'center',behavior:'smooth'});formRef.current?.querySelector('input')?.focus();});}
 function field(key:keyof Editor,value:string){setEditor(e=>e?{...e,[key]:value}:null);}
 async function save(event:React.FormEvent){event.preventDefault();if(!editor||lock.current)return;lock.current=true;setBusy(true);setError('');setSuccess('');
 try{const body={kind:editor.kind,id:editor.id,name:editor.name,code:editor.code,description:editor.description,defaultTechnicianId:editor.defaultTechnicianId||null,defaultLat:editor.lat.trim()===''?null:Number(editor.lat),defaultLng:editor.lng.trim()===''?null:Number(editor.lng),expected:editor.expected};const response=await fetch('/api/admin/master-data',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const result=await response.json();if(!response.ok)throw Error(result.error||'บันทึกไม่สำเร็จ');setEditor(null);setSuccess('บันทึกข้อมูลเรียบร้อยแล้ว');router.refresh();}catch(e){setError(e instanceof Error?e.message:'บันทึกไม่สำเร็จ');}finally{setBusy(false);lock.current=false;}}
 const input='mt-2 block w-full rounded-lg border border-slate-300 bg-white p-3 text-sm';
 return <div className="space-y-8">{success&&<p role="status" className="rounded-xl bg-emerald-50 p-4 text-emerald-800">{success}</p>}
 {editor&&<form ref={formRef} onSubmit={save} className="space-y-5 rounded-2xl border border-slate-200 bg-white p-6"><h2 className="text-xl font-semibold">{editor.id?'แก้ไข':'เพิ่ม'}{editor.kind==='building'?'อาคาร':'หมวดหมู่'}</h2>{error&&<p role="alert" className="rounded-lg bg-red-50 p-3 text-red-700">{error}</p>}<fieldset disabled={busy} className="grid gap-5 sm:grid-cols-2"><label className="text-sm">ชื่อ{editor.kind==='building'?'อาคาร':'หมวดหมู่'} *<input required maxLength={160} className={input} value={editor.name} onChange={e=>field('name',e.target.value)}/></label>
 {editor.kind==='building'?<><label className="text-sm">รหัสอาคาร *<input required maxLength={32} pattern="[A-Za-z0-9_-]+" className={input} value={editor.code} onChange={e=>field('code',e.target.value)}/><span className="text-xs text-slate-500">ตัวอักษรอังกฤษ ตัวเลข - หรือ _</span></label><label className="text-sm">ละติจูด<input type="number" step="any" min={-90} max={90} className={input} value={editor.lat} onChange={e=>field('lat',e.target.value)}/></label><label className="text-sm">ลองจิจูด<input type="number" step="any" min={-180} max={180} className={input} value={editor.lng} onChange={e=>field('lng',e.target.value)}/></label><div className="space-y-3 sm:col-span-2"><div><h3 className="font-semibold text-slate-900">เลือกพิกัดจากแผนที่</h3><p className="mt-1 text-sm text-slate-500">คลิกบนแผนที่หรือลากหมุด ระบบจะกรอกละติจูดและลองจิจูดให้อัตโนมัติ</p></div><LocationPickerMap key={`building-${editor.id??'new'}`} initialLat={coordinate(editor.lat,14.9928,-90,90)} initialLng={coordinate(editor.lng,103.1025,-180,180)} onLocationSelect={(lat,lng)=>setEditor(current=>current?{...current,lat:lat.toFixed(6),lng:lng.toFixed(6)}:null)}/></div><p className="text-sm text-slate-500 sm:col-span-2">พิกัดใหม่จะอัปเดตตำแหน่งอาคาร และซิงค์ตำแหน่งหมุดของคำร้องในอาคารนี้บนแผนที่ภาพรวมอัตโนมัติ</p></>:<><label className="text-sm">คำอธิบาย<textarea maxLength={500} rows={3} className={input} value={editor.description} onChange={e=>field('description',e.target.value)}/></label><label className="text-sm">ช่างประจำหมวดหมู่<select className={input} value={editor.defaultTechnicianId} onChange={e=>field('defaultTechnicianId',e.target.value)}><option value="">ไม่มอบหมายอัตโนมัติ</option>{technicians.map(t=><option key={t.id} value={t.id}>{t.name} — {t.department||'ช่างซ่อมบำรุง'}</option>)}</select></label></>}</fieldset><div className="flex gap-3"><button disabled={busy} className="rounded-lg bg-slate-900 px-5 py-3 text-sm text-white disabled:opacity-50">{busy?'กำลังบันทึก…':'บันทึก'}</button><button disabled={busy} type="button" onClick={()=>setEditor(null)} className="rounded-lg border px-5 py-3 text-sm">ยกเลิก</button></div></form>}
 <section className="rounded-2xl border border-slate-200 bg-white p-5 sm:p-6"><div className="mb-5 flex items-center justify-between gap-3"><h2 className="text-xl font-semibold">อาคาร ({buildings.length})</h2><button disabled={busy} onClick={()=>open(fresh('building'))} className="shrink-0 rounded-lg bg-slate-900 px-4 py-2.5 text-sm font-semibold text-white">เพิ่มอาคาร</button></div><div className="grid gap-3 lg:grid-cols-2">{buildings.map(b=><article key={b.id} className="rounded-xl border border-slate-200 bg-slate-50 p-4"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><h3 className="font-semibold text-slate-900">{b.name}</h3><p className="mt-1 font-mono text-sm text-indigo-700">{b.code}</p></div><button disabled={busy} aria-label={'แก้ไขอาคาร '+b.name} className="shrink-0 rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm font-semibold hover:bg-slate-100" onClick={()=>open({kind:'building',id:b.id,name:b.name,code:b.code,lat:b.defaultLat?.toString()??'',lng:b.defaultLng?.toString()??'',description:'',defaultTechnicianId:'',expected:JSON.stringify(b)})}>แก้ไข</button></div><p className="mt-3 break-words text-sm text-slate-600"><span className="font-semibold text-slate-700">พิกัด:</span> {b.defaultLat!==null&&b.defaultLng!==null?`${b.defaultLat}, ${b.defaultLng}`:'ยังไม่มีพิกัด'}</p></article>)}</div>{!buildings.length&&<p className="py-5 text-sm text-slate-500">ยังไม่มีอาคาร</p>}</section>
 <section className="rounded-2xl border border-slate-200 bg-white p-6"><div className="mb-5 flex items-center justify-between"><h2 className="text-xl font-semibold">หมวดหมู่ ({categories.length})</h2><button disabled={busy} onClick={()=>open(fresh('category'))} className="rounded-lg bg-slate-900 px-4 py-2 text-sm text-white">เพิ่มหมวดหมู่</button></div><ul className="divide-y">{categories.map(c=><li key={c.id} className="flex items-start justify-between gap-4 py-4"><div><h3 className="font-medium">{c.name}</h3><p className="mt-1 whitespace-pre-wrap text-sm text-slate-500">{c.description||'ไม่มีคำอธิบาย'}</p><p className="mt-1 text-sm font-medium text-indigo-700">{c.defaultTechnicianId?'มอบหมายอัตโนมัติ: '+(technicians.find(t=>t.id===c.defaultTechnicianId)?.name||'ช่างที่กำหนด'):'ยังไม่มอบหมายอัตโนมัติ'}</p></div><button disabled={busy} aria-label={'แก้ไขหมวดหมู่ '+c.name} className="text-sm underline" onClick={()=>open({kind:'category',id:c.id,name:c.name,code:'',lat:'',lng:'',description:c.description??'',defaultTechnicianId:c.defaultTechnicianId??'',expected:JSON.stringify(c)})}>แก้ไข</button></li>)}</ul>{!categories.length&&<p className="py-5 text-sm text-slate-500">ยังไม่มีหมวดหมู่</p>}</section></div>;
}
