"use client";
import {useRef,useState} from 'react';import {useRouter} from 'next/navigation';
export default function TicketLifecycleActions({ticketId,status,updatedAt,admin,owner}:{ticketId:string;status:string;updatedAt:string;admin:boolean;owner:boolean}){
 const closed=['COMPLETED','REJECTED','CANCELLED'].includes(status);const actions=admin?(closed?[['reopen','เปิดงานใหม่']]:[['reject','ไม่รับดำเนินการ'],['cancel','ยกเลิกคำร้อง']]):owner&&status==='PENDING'?[['cancel','ยกเลิกคำร้อง']]:[];
 const [action,setAction]=useState('');const [reason,setReason]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);const lock=useRef(false);const router=useRouter();
 if(!actions.length)return null;
 async function submit(e:React.FormEvent){e.preventDefault();if(lock.current)return;lock.current=true;setBusy(true);setError('');try{const r=await fetch('/api/tickets/lifecycle',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({ticketId,action,reason,expectedUpdatedAt:updatedAt})});const data=await r.json();if(!r.ok)throw Error(data.error);setAction('');setReason('');router.refresh();}catch(e){setError(e instanceof Error?e.message:'บันทึกไม่สำเร็จ');}finally{lock.current=false;setBusy(false);}}
 return <section className="rounded-2xl border border-slate-200 bg-white p-6"><h2 className="font-semibold">จัดการคำร้อง</h2>{!action?<div className="mt-4 flex flex-wrap gap-3">{actions.map(([value,label])=><button key={value} className="rounded-lg border border-slate-300 px-4 py-2 text-sm" onClick={()=>setAction(value)}>{label}</button>)}</div>:<form onSubmit={submit} className="mt-4 space-y-4"><p className="text-sm text-slate-600">{action==='reopen'?'งานจะกลับให้ช่างล่าสุด หรือรอรับเรื่องหากยังไม่มีช่าง ผลประเมินเดิมเก็บไว้ในประวัติและจะประเมินใหม่ได้หลังซ่อมเสร็จ':'งานจะหยุดดำเนินการและเก็บประวัติไว้ ผู้ดูแลสามารถเปิดงานใหม่ได้'}</p><label className="block text-sm">เหตุผล *<textarea required maxLength={2000} disabled={busy} className="mt-2 w-full rounded-lg border p-3" value={reason} onChange={e=>setReason(e.target.value)}/></label>{error&&<p role="alert" className="text-sm text-red-700">{error}</p>}<div className="flex gap-3"><button disabled={busy} className="rounded-lg bg-slate-900 px-4 py-2 text-sm text-white">{busy?'กำลังบันทึก…':'ยืนยัน'+actions.find(a=>a[0]===action)?.[1]}</button><button type="button" disabled={busy} className="rounded-lg border px-4 py-2 text-sm" onClick={()=>{setAction('');setError('');}}>กลับ</button></div></form>}</section>;
}
