import {requireCurrentUser} from '@/lib/auth';
import {prisma} from '@/lib/prisma';
import {isAdmin,latestAssignmentOrder} from '@/lib/permissions';
import AccessDenied from '@/components/AccessDenied';
import ReportFilters from '@/components/ReportFilters';
import {reportFilter,reportMetrics,statusLabels,type ReportParams} from '@/lib/reporting';
import ReportCharts from '@/components/ReportCharts';
export default async function AdminDashboardPage({searchParams}:{searchParams:Promise<ReportParams>}){
 const user=await requireCurrentUser('/admin/dashboard');if(!isAdmin(user))return <AccessDenied message="รายงานสำหรับผู้ดูแลระบบเท่านั้น"/>;
 let filter;try{filter=reportFilter(await searchParams);}catch(e){return <div role="alert" className="p-8">{e instanceof Error?e.message:'ตัวกรองไม่ถูกต้อง'} <a href="/admin/dashboard">ล้างตัวกรอง</a></div>;}
 const [tickets,buildings,categories,technicians]=await Promise.all([
 prisma.ticket.findMany({where:filter.where,include:{evaluation:true,assignments:{orderBy:latestAssignmentOrder,take:1}},orderBy:[{createdAt:'desc'},{id:'desc'}]}),
 prisma.building.findMany({orderBy:{name:'asc'}}),prisma.category.findMany({orderBy:{name:'asc'}}),prisma.user.findMany({where:{role:'TECHNICIAN'},orderBy:{name:'asc'}})]);
 const m=reportMetrics(tickets);const suffix=filter.query?'?'+filter.query:'';
 return <div className="mx-auto max-w-6xl space-y-8 px-4 py-10 sm:px-6">
 <header className="flex flex-wrap items-center justify-between gap-4"><div><h1 className="text-3xl font-semibold tracking-tight">สถิติและรายงานงานซ่อม</h1><p className="mt-3 text-sm text-slate-500">กรองตามวันที่แจ้ง เวลาไทย • รายงานและไฟล์ส่งออกใช้ตัวกรองเดียวกัน</p></div><div className="flex gap-3"><a className="rounded-lg border p-3 text-sm" href={'/api/admin/export-excel'+suffix}>ดาวน์โหลด Excel</a><a className="rounded-lg bg-slate-900 p-3 text-sm text-white" target="_blank" href={'/admin/reports/pdf'+suffix}>พิมพ์ / PDF</a></div></header>
 <ReportFilters values={filter.values} buildings={buildings} categories={categories}/>
 <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[['คำร้องตามตัวกรอง',m.total+' รายการ','เสร็จแล้ว '+m.completed+' รายการ'],['อัตราซ่อมสำเร็จ',m.resolutionRate+'%','งานเสร็จ / คำร้องทั้งหมดตามตัวกรอง'],['เวลาเฉลี่ยจนซ่อมเสร็จ',m.avgHours===null?'ยังไม่มีข้อมูล':m.avgHours+' ชม.','ตั้งแต่แจ้งถึงเสร็จ รวมเวลารอ จาก '+m.durationCount+' งาน'],['ความพึงพอใจ',m.avgRating+(m.ratedCount?' / 5':''),'จาก '+m.ratedCount+' การประเมิน']].map(([label,value,detail])=><section key={label} className="rounded-2xl border border-slate-200 bg-white p-6"><h2 className="text-sm text-slate-500">{label}</h2><p className="my-3 text-2xl font-semibold">{value}</p><p className="text-xs leading-6 text-slate-500">{detail}</p></section>)}</div>
 {!tickets.length&&<p role="status" className="rounded-xl bg-slate-100 p-6">ไม่พบคำร้องตามตัวกรองนี้</p>}
 <ReportCharts status={Object.entries(statusLabels).map(([key,name])=>({name,value:tickets.filter(t=>t.status===key).length})).filter(x=>x.value>0)} category={categories.map(x=>({name:x.name,value:tickets.filter(t=>t.categoryId===x.id).length})).filter(x=>x.value>0)} building={buildings.map(x=>({name:x.name,value:tickets.filter(t=>t.buildingId===x.id).length})).filter(x=>x.value>0)}/>
 <p className="text-xs text-slate-500">เวลาเฉลี่ยไม่ใช่ SLA: ระบบยังไม่มีเกณฑ์เวลาที่ตกลงไว้ งานที่ไม่มีวันเสร็จหรือวันเสร็จก่อนวันแจ้งไม่นำมาคำนวณ</p>
 <div className="grid gap-6 md:grid-cols-2">{[{label:'จำนวนตามหมวดหมู่',items:categories,key:'categoryId' as const},{label:'จำนวนตามอาคาร',items:buildings,key:'buildingId' as const}].map(group=><section className="rounded-2xl border bg-white p-6" key={group.key}><h2 className="mb-6 text-lg font-semibold">{group.label}</h2><div className="space-y-4">{group.items.map(item=>{const count=tickets.filter(t=>t[group.key]===item.id).length;const percent=m.total?count/m.total*100:0;return <div key={item.id}><div className="flex justify-between gap-4 text-sm"><span>{item.name}</span><span>{count} รายการ</span></div><div className="mt-2 h-2 rounded bg-slate-100"><div className="h-2 rounded bg-slate-700" style={{width:percent+'%'}}/></div></div>;})}</div></section>)}</div>
 <section className="rounded-2xl border bg-white p-5 sm:p-6"><h2 className="text-lg font-semibold">งานตามผู้รับผิดชอบล่าสุด</h2><p className="my-3 text-sm text-slate-500">นับคำร้องละครั้งตามตัวกรอง ช่างคนก่อนจะไม่ถูกนับซ้ำ • งานค้างไม่ใช่สถานะความพร้อมของช่าง</p><div className="grid gap-3 md:hidden">{technicians.map(tech=>{const jobs=tickets.filter(t=>t.assignments[0]?.technicianId===tech.id);const stats=reportMetrics(jobs);return <article key={tech.id} className="rounded-xl border bg-slate-50 p-4"><h3 className="font-semibold">{tech.name}</h3><div className="mt-3 grid grid-cols-2 gap-3 text-sm"><p>งานทั้งหมด <b className="block text-lg">{stats.total}</b></p><p>เสร็จแล้ว <b className="block text-lg text-emerald-700">{stats.completed}</b></p><p>งานค้าง <b className="block text-lg text-amber-700">{jobs.filter(t=>['IN_PROGRESS','WAITING_PARTS'].includes(t.status)).length}</b></p><p>คะแนนเฉลี่ย <b className="block text-lg">{stats.avgRating}</b></p></div></article>})}</div><div className="hidden overflow-x-auto md:block"><table className="w-full text-left text-sm"><thead><tr>{['ช่าง','งานทั้งหมด','เสร็จแล้ว','งานค้าง','คะแนนเฉลี่ย'].map(h=><th key={h} className="border-b p-3">{h}</th>)}</tr></thead><tbody>{technicians.map(tech=>{const jobs=tickets.filter(t=>t.assignments[0]?.technicianId===tech.id);const stats=reportMetrics(jobs);return <tr key={tech.id}><td className="p-3">{tech.name}</td><td className="p-3">{stats.total}</td><td className="p-3">{stats.completed}</td><td className="p-3">{jobs.filter(t=>['IN_PROGRESS','WAITING_PARTS'].includes(t.status)).length}</td><td className="p-3">{stats.avgRating}</td></tr>;})}</tbody></table></div></section>
 <section className="rounded-2xl border bg-white p-6"><h2 className="mb-4 text-lg font-semibold">รายการที่ใช้คำนวณ ({m.total})</h2><div className="space-y-3">{tickets.map(t=><a key={t.id} href={'/tickets/'+t.id} className="flex flex-wrap justify-between gap-3 border-b py-3 text-sm"><span>{t.ticketCode} · {t.title}</span><span>{statusLabels[t.status]||t.status}</span></a>)}</div></section>
 </div>;
}
